version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}

      - checkout

      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive

      - save_cache:
          key: source-v1-{{ .Branch }}
          paths:
            - ".git"

      - run:
          name: Build Mxnet Cuda 10.0 Docker Image
          command: |
               cd ~
               mv ~/project/trueface-docker/Dockerfile.mxnetcuda10.0 ~
               docker build -t trueface/mxnet-cuda10.0 -f Dockerfile.mxnetcuda10.0 .
               docker run --name mxcuda10.0-tmp trueface/mxnet-cuda10.0 /bin/true
               docker cp mxcuda10.0-tmp:/mxnet-cuda10.0-archive.tgz ~/mxnet-cuda10.0-archive.tgz
               docker rm mxcuda10.0-tmp

      - store_artifacts:
          path: ~/mxnet-cuda10.0-archive.tgz



